AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my-user-sam

  Sample SAM Template for my-user-sam

Globals:
  Function:
    Timeout: 20
    Architectures:
      - x86_64
    MemorySize: 512
    Environment:
      Variables:
        MY_COGNITO_POOL_CLIENT_ID: AQICAHgIlLUJE69KByxGFM2/8VYxJNThjm98ueSExZou1hukqwHfz5wWWm3cA98ZC3DrVFdmAAAAeDB2BgkqhkiG9w0BBwagaTBnAgEAMGIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBe5IlwgL2sYrT070AgEQgDVhADUVcXmH06oXDFUEJllTUo0O4O9/jxVarY63o0qY0QIVdCddQY0vtfG0f8r7M98gRnb4qA==
        MY_COGNITO_POOL_CLIENT_SECRET: AQICAHgIlLUJE69KByxGFM2/8VYxJNThjm98ueSExZou1hukqwG7P/KwZTaK9E4L1h34wiWCAAAAlDCBkQYJKoZIhvcNAQcGoIGDMIGAAgEAMHsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQML3LO30UbRKxsZLlQAgEQgE4RsXHL5AIRlll5/JP1ETpOUWbs3v8kwPCs6QGNvfD3xiNvJMAI6ezw3hCiJnLUX6mStiknnT63DpsjFWLeW2djSeHsfaaJKImXZtC4gG0=
        MY_COGNITO_POOL_ID: AQICAHgIlLUJE69KByxGFM2/8VYxJNThjm98ueSExZou1hukqwEpgUGUjhrGhgfRBqwggGD0AAAAcTBvBgkqhkiG9w0BBwagYjBgAgEAMFsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPRuYIBXVg6Ud8GkDAgEQgC5melJGUWLYUHz6whCnvjkUk13TcPoH1s96ClhuHQxyOIDYdsKrQqbLG6RwNxjd
Resources:
  MyUserSignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MyUserSam
      Handler: dev.jeffersonfreitas.myusersam.MyUserSignUp::handleRequest
      Runtime: java11
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        MyUserSignUp:
          Type: Api
          Properties:
            Path: /sign-up
            Method: post
  MyUserConfirmSignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MyUserSam
      Handler: dev.jeffersonfreitas.myusersam.MyUserConfirmSignUp::handleRequest
      Runtime: java11
      Events:
        MyUserSignUp:
          Type: Api
          Properties:
            Path: /confirm-sign-up
            Method: post
  MyUserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MyUserSam
      Handler: dev.jeffersonfreitas.myusersam.MyUserLogin::handleRequest
      Runtime: java11
      Events:
        MyUserSignUp:
          Type: Api
          Properties:
            Path: /login
            Method: post
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
Outputs:
  MyUserSignUpApi:
    Description: "API Gateway endpoint URL for Prod stage for MyUserSignUpFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  MyUserSignUpFunction:
    Description: "MyUserSignUpFunction Lambda Function ARN"
    Value: !GetAtt MyUserSignUpFunction.Arn
  MyUserSignUpFunctionIamRole:
    Description: "Implicit IAM Role created for MyUserSignUpFunction"
    Value: !GetAtt MyUserSignUpFunctionRole.Arn
