AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my-user-sam

  Sample SAM Template for my-user-sam

Globals:
  Function:
    Timeout: 20
    Architectures:
      - x86_64
    MemorySize: 512
#    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
#      Variables:
#        PARAM1: VALUE
#        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/

Resources:
  MyUserSignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MyUserSam
      Handler: dev.jeffersonfreitas.myusersam.MyUserSignUp::handleRequest
      Runtime: java11
      Events:
        MyUserSignUp:
          Type: Api
          Properties:
            Path: /sign-up
            Method: post

Outputs:
  MyUserSignUpApi:
    Description: "API Gateway endpoint URL for Prod stage for MyUserSignUpFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  MyUserSignUpFunction:
    Description: "MyUserSignUpFunction Lambda Function ARN"
    Value: !GetAtt MyUserSignUpFunction.Arn
  MyUserSignUpFunctionIamRole:
    Description: "Implicit IAM Role created for MyUserSignUpFunction"
    Value: !GetAtt MyUserSignUpFunctionRole.Arn
